### ISSUE TITLE
G26 

### ISSUE THREAD

**Issue by davidchapman121** [somiyagawa/SINUHE-the-Hierotyper#1]
Hi So,
When I try to type G26 it displays the glyph for G25 instead. G26 should be an ibis on a stand
𓅝.
But it instead inputs this
𓅜
I tried to submit a pull  request to rectify this but Github did not allow me to do so.

The spelling of DHwty should also be checked as it incorrectly uses G25. It should use G26 (as below) 
𓅝𓏏𓏭𓀭　

Hope this helps
David
- My thanks to Susanne Binder for her encouragement and thought provoking conversation

**Comment by davidchapman121** [comment]
I have now submitted pull requests.
Thanks
David

**Comment by davidchapman121** [comment]
I accidentally submitted two pull requests. I am new to GitHub and am still learning both address issue 1

**Comment by somiyagawa** [comment]
Thank you for your contribution! That's awesome. I merged them.

**Comment by davidchapman121** [comment]
I made a slight fix to remove an extra space.  Everything should work in google input as expected  with the new patch
see #4.
Thanks
